### ISSUE TITLE
The simpler transform is semantically wrong

### ISSUE THREAD

**Issue by 3cp** [sidvishnoi/esm-to-cjs#4]
I came to your interesting package in searching of a lighter esm to cjs transformer.

But I noticed the code is semantically wrong which can lead to logic error.

Your example
```js
// input
import { resolve as resolvePath } from "path";
resolvePath("./hello")

// what i wanted
const {  resolve: resolvePath } = require("path");
resolvePath("./hello")
```

Translated the esm import to a simple variable, this is wrong in esm semantic. There is a reason why all babel/TS transforms esm import into verbose `a_namespace.an_exported_name`, because in esm standard, the import **does not create a local JS variable, it's a read-only property on the namespace of that esm module**.

Consider following proof, create two local files:
`foo.mjs`
```js
let foo = 1;
function increaseFoo() {
  foo += 1;
}
export { foo, increaseFoo };
```
`index.mjs`
```js
import { foo, increaseFoo } from './foo.mjs';
console.log('foo is ' + foo);
increaseFoo();
console.log('foo is ' + foo);
```
Then use nodejs v12 or above
```bash
node --experimental-modules index.mjs
```
It prints out:
```
foo is 1
foo is 2
```
You can see that `foo` inside `index.mjs` is not a local variable, otherwise it cannot be mutated.

**Comment by sidvishnoi** [comment]
You're right. I didn't think of it this way. Thanks for reporting!
Unfortunately, I don't think I will fix this, as I don't use this project anymore and it has served me well the way I used it. PR welcome though. I'll add it in readme otherwise.

**Comment by 3cp** [comment]
I understand, most code do not expose this kind of edge case.
BTW, any other alternative (of babel and tsc) you know of?

**Comment by sidvishnoi** [comment]
> I understand,

Thank you :slightly_smiling_face:

>  BTW, any other alternative (of babel and tsc) you know of?

Umm no. I started using ES modules in general (Node 12+ and Deno) or Rollup in most cases.
